### ISSUE TITLE
"Made with Rust" Badge has incorrect dimensions

### ISSUE THREAD

**Issue by GandalfTheGrayOfHell** [BraveUX/for-the-badge#117]
As the title says, the "Made with Rust" SVG is larger than the standard "Made with LANGUAGE_XYZ" SVG.

Here are few SVGs that have correct dimensions:
1) [Python](https://raw.githubusercontent.com/BraveUX/for-the-badge/master/src/images/badges/made-with-python.svg)
2) [Java](https://forthebadge.com/images/badges/made-with-java.svg)
3) [C#](https://forthebadge.com/images/badges/made-with-c-sharp.svg)
4) [C++](https://forthebadge.com/images/badges/made-with-c-plus-plus.svg)

Here is the out of proportion Rust badge: [Rust](https://raw.githubusercontent.com/BraveUX/for-the-badge/master/src/images/badges/made-with-rust.svg)

Here is the output example from [StackEdit](https://stackedit.io/)

![Side_by_side](https://user-images.githubusercontent.com/2004372/96722987-a3a94380-13cb-11eb-9da2-f6e398487a69.png)

There are workarounds to solve this but a resize to the SVG will make all the badges uniform in size.

**Comment by ekfuhrmann** [comment]
Looks great, thanks for the contribution!

**Comment by ekfuhrmann** [comment]
Resolved with #118
