### ISSUE TITLE
Badge ideas

### ISSUE THREAD

**Issue by Andre601** [BraveUX/for-the-badge#122]
I'm not experienced enough to try and work on some SVGs, but I think that I would have some interesting badge ideas that could be fun to use.

My Badge ideas (I used shields.io to generate those badges)

![you](https://img.shields.io/static/v1?label=Built%20For&message=You&color=c13b3a&labelColor=ea4560&style=for-the-badge)
![pogchamps](https://img.shields.io/static/v1?label=Built%20For&message=Pogchamps&color=c13b3a&labelColor=ea4560&style=for-the-badge)
![experience](https://img.shields.io/static/v1?label=Built%20With&message=Experience&color=d15e28&labelColor=e36d26&style=for-the-badge)
![cuteness](https://img.shields.io/static/v1?label=May%20Contain&message=Cuteness&color=c13b3a&labelColor=ea4560&style=for-the-badge)
![code](https://img.shields.io/static/v1?label=May%20Contain&message=Code&color=c13b3a&labelColor=ea4560&style=for-the-badge)
![nothing](https://img.shields.io/static/v1?label=May%20Contain&message=Nothing&color=c13b3a&labelColor=ea4560&style=for-the-badge)
![fun](https://img.shields.io/static/v1?label=May%20Contain&message=Fun&color=c13b3a&labelColor=ea4560&style=for-the-badge)

Since my idea has mostly "May contain" would I suggest to put this under its own category.
I hope those pages are a nice idea.

**Comment by ekfuhrmann** [comment]
I'm excited to announce that we have now added a [**For The Badge Generator**](https://forthebadge.com/generator/) which allows you to build the badge to whatever specifications you want! Feel free to give it a whirl!

Still interested in submitting a badge for public sharing and hosting on For The Badge? You can still submit a PR with the badge you created by providing a share link, and if it gets enough support or really sings to us, we'll add it to the core site!
