### ISSUE TITLE
Add a badge for Bash and Linux 

### ISSUE THREAD

**Issue by Blastoise** [BraveUX/for-the-badge#123]
I would love to use Bash and Linux badges.

**Comment by ekfuhrmann** [comment]
I'm excited to announce that we have now added a [**For The Badge Generator**](https://forthebadge.com/generator/) which allows you to build the badge to whatever specifications you want! Feel free to give it a whirl!

Still interested in submitting a badge for public sharing and hosting on For The Badge? You can still submit a PR with the badge you created by providing a share link, and if it gets enough support or really sings to us, we'll add it to the core site!
