### ISSUE TITLE
Following the shields.io standard

### ISSUE THREAD

**Issue by stuartpb** [BraveUX/for-the-badge#13]
These badges don't fit in with other badges at all: it would be easier to integrate them if they followed the template established by http://shields.io.

**Comment by jaxgeller** [comment]
@stuartpb, thanks for the issue but we made For the Badge as a joke to make fun of the standard badges like http://shields.io. Check out the about section on our site http://forthebadge.com for further details.

**Comment by emrehan** [comment]
I'd still prefer to put these next to other badges.

**Comment by Efreak** [comment]
[Check the bottom of shields.io](http://shields.io/#styles). Making custom badges from shields.io is fairly easy: ![](https://img.shields.io/badge/color-ship_it-blue.svg).


Basically, `https://img.shields.io/badge/<SUBJECT>-<STATUS>-color.svg` gets you ![](https://img.shields.io/badge/%3CSUBJECT%3E-%3CSTATUS%3E-brightgreen.svg), and there's a bunch of other parameters available too, for styling, links, etc

**Comment by christoga** [comment]
In my opinion, **forthebadge** is way cooler than **shields**.
**Forthebadge** interface is really good.

**Comment by Efreak** [comment]
> forthebadge is way cooler than shields

I absolutely agree. However, it entirely solves the issue of

> These badges don't fit in with other badges at all
