### ISSUE TITLE
New Badge request

### ISSUE THREAD

**Issue by Pukimaa** [BraveUX/for-the-badge#131]
It would be cool if there would be a Badge `USES | SCSS` like the `USES | CSS`

**Comment by Pukimaa** [comment]
I nade a pr for that now: https://github.com/BraveUX/for-the-badge/pull/132

Preview:
![uses-scss](https://user-images.githubusercontent.com/58347116/116049119-3924d900-a676-11eb-9462-97dbe31820b4.png)

**Comment by ekfuhrmann** [comment]
I'm excited to announce that we have now added a [**For The Badge Generator**](https://forthebadge.com/generator/) which allows you to build the badge to whatever specifications you want! Feel free to give it a whirl!

Still interested in submitting a badge for public sharing and hosting on For The Badge? You can still submit a PR with the badge you created by providing a share link, and if it gets enough support or really sings to us, we'll add it to the core site!
