### ISSUE TITLE
New Badge Request

### ISSUE THREAD

**Issue by codelixir** [BraveUX/for-the-badge#137]
Can we have a `Made With | Flutter *`  badge?  Like Made with Python, etc but with the Flutter logo (The logo is slightly complex, but I found a simple version with a single colour as shown below but with white instead of black)

![Flutter Logo](https://cdn.icon-icons.com/icons2/2389/PNG/512/flutter_logo_icon_145273.png)

**Comment by sven-frotscher** [comment]
![made with: Flutter](https://img.shields.io/static/v1?label=made%20with&message=Flutter&logo=flutter&style=for-the-badge&color=c13d3b&labelColor=ea4761) (https://img.shields.io/static/v1?label=made%20with&message=Flutter&logo=flutter&style=for-the-badge&color=c13d3b&labelColor=ea4761)
is the closest I could get on [shields.io](https://shields.io).

**Comment by codelixir** [comment]
> ![made with: Flutter](https://camo.githubusercontent.com/0b5ac0fceaa03c8671892b501b443eaf585d2a3daf44c970b09f134effd3d92d/68747470733a2f2f696d672e736869656c64732e696f2f7374617469632f76313f6c6162656c3d6d61646525323077697468266d6573736167653d466c7574746572266c6f676f3d666c7574746572267374796c653d666f722d7468652d626164676526636f6c6f723d633133643362266c6162656c436f6c6f723d656134373631) (https://img.shields.io/static/v1?label=made%20with&message=Flutter&logo=flutter&style=for-the-badge&color=c13d3b&labelColor=ea4761)
> is the closest I could get on [shields.io](https://shields.io).

Thank you! This is amazing
Can one of the project managers please add this?

**Comment by sven-frotscher** [comment]
It's slightly inconsistent with the existing `Made with: ` badges (where the logo is on the right).
[shields.io](https://shields.io) puts the logo on the left.

**Comment by sven-frotscher** [comment]
For comparison:
![Made with: Flutter (shields.io)](https://img.shields.io/static/v1?label=made%20with&message=Flutter&logo=flutter&style=for-the-badge&color=c13d3b&labelColor=ea4761)
![Made with: Python (forthebadge.com)](https://forthebadge.com/images/badges/made-with-python.svg)

Differences are:
* The colour schemes (I took the red colours from ![Built for: Android](https://forthebadge.com/images/badges/built-for-android.svg)). That is relatively easy to fix, just needing different values for the `color` and `labelColor` parameters.
* The Shields badge(s) is/are smaller than the For the Badge ones
* Shields puts the logo(s) at the very left, For the Badge at the very right

In addition, using the Shields badge or an eventual ForTheBadge-created one may violate the [Flutter Brand Guidelines](https://flutter.dev/brand), but I'm not sure.

**Comment by ekfuhrmann** [comment]
I'm excited to announce that we have now added a [**For The Badge Generator**](https://forthebadge.com/generator/) which allows you to build the badge to whatever specifications you want! Feel free to give it a whirl!

In this case it looks like you also want to incorporate an icon. I haven't yet gotten around to adding icon support to the badge generator yet (though it is on my list of things to do), but hopefully in the meantime this will cover your bases!

Still interested in submitting a badge for public sharing and hosting on For The Badge? You can still submit a PR with the badge you created by providing a share link, and if it gets enough support or really sings to us, we'll add it to the core site!
