### ISSUE TITLE
Dynamically Generating Badges

### ISSUE THREAD

**Issue by IndianBoy6** [BraveUX/for-the-badge#140]
Sorry, this isn't really an issue/enhancement but I thought this would be the best place to ask a question. Is there a way I can generate a badge with the text `Cool Badge` with a red background (or any other badge)? I tried looking through the SVG but it wasn't very helpful to determine how to render each character individually.

**Comment by sven-frotscher** [comment]
You can generate them on https://shields.io.

For example, ![cool: badge](https://shields.io/badge/cool-badge-red?style=for-the-badge) is https://shields.io/badge/cool-badge-red?style=for-the-badge.

You may have to look up the colour codes for (e.g.) the correct red background for both parts.

**Comment by IndianBoy6** [comment]
That's exactly what I was looking for. Thanks!
