### ISSUE TITLE
Please Add Made With Dart 🥺 

### ISSUE THREAD

**Issue by Lakhankumawat** [BraveUX/for-the-badge#142]
As i am a flutter developer but i didn't found any badges for either flutter or dart language . I request  admin to please try to add those .

**Comment by ekfuhrmann** [comment]
I'm excited to announce that we have now added a [**For The Badge Generator**](https://forthebadge.com/generator/) which allows you to build the badge to whatever specifications you want! Feel free to give it a whirl!

Still interested in submitting a badge for public sharing and hosting on For The Badge? You can still submit a PR with the badge you created by providing a share link, and if it gets enough support or really sings to us, we'll add it to the core site!

**Comment by Lakhankumawat** [comment]
> I'm excited to announce that we have now added a [**For The Badge Generator**](https://forthebadge.com/generator/) which allows you to build the badge to whatever specifications you want! Feel free to give it a whirl!
> 
> Still interested in submitting a badge for public sharing and hosting on For The Badge? You can still submit a PR with the badge you created by providing a share link, and if it gets enough support or really sings to us, we'll add it to the core site!

`https://forthebadge.com/generator/ ` <br>  *it looks Great thanks for help !*
