### ISSUE TITLE
New Badge Request

### ISSUE THREAD

**Issue by TheFruxz** [BraveUX/for-the-badge#144]
Can you please add an `Made With | Kotlin` Badge?

**Comment by ekfuhrmann** [comment]
I'm excited to announce that we have now added a [**For The Badge Generator**](https://forthebadge.com/generator/) which allows you to build the badge to whatever specifications you want! Feel free to give it a whirl!

Still interested in submitting a badge for public sharing and hosting on For The Badge? You can still submit a PR with the badge you created by providing a share link, and if it gets enough support or really sings to us, we'll add it to the core site!
