### ISSUE TITLE
Custom badges do not seem to work.

### ISSUE THREAD

**Issue by CodingSpecies** [BraveUX/for-the-badge#170]
When I seem to make a custom badge, and copy the markdown, for my README.md files, the badge appears with its alt text. Thank you.

I would like to see this:
![image](https://user-images.githubusercontent.com/70807500/129874234-7657cb9f-916d-4a71-975d-d4723b276c96.png)

But This is what it shows:
[![forthebadge](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDkuNjUiIGhlaWdodD0iMzUiIHZpZXdCb3g9IjAgMCAxMDkuNjUgMzUiPjxyZWN0IGNsYXNzPSJzdmdfX3JlY3QiIHg9IjAiIHk9IjAiIHdpZHRoPSI1MS41OSIgaGVpZ2h0PSIzNSIgZmlsbD0iIzMxQzRGMyIvPjxyZWN0IGNsYXNzPSJzdmdfX3JlY3QiIHg9IjQ5LjU5IiB5PSIwIiB3aWR0aD0iNjAuMDYiIGhlaWdodD0iMzUiIGZpbGw9IiMzODlBRDUiLz48cGF0aCBjbGFzcz0ic3ZnX190ZXh0IiBkPSJNMTMuOTcgMTguMTNMMTMuOTcgMTguMTNMMTMuOTcgMTcuNDZRMTMuOTcgMTUuNTMgMTQuOTAgMTQuNDRRMTUuODIgMTMuMzUgMTcuNDggMTMuMzVMMTcuNDggMTMuMzVRMTguOTAgMTMuMzUgMTkuNzQgMTQuMDVRMjAuNTggMTQuNzYgMjAuNzUgMTYuMDhMMjAuNzUgMTYuMDhMMTkuMzAgMTYuMDhRMTkuMDUgMTQuNTQgMTcuNTEgMTQuNTRMMTcuNTEgMTQuNTRRMTYuNTEgMTQuNTQgMTYuMDAgMTUuMjZRMTUuNDggMTUuOTggMTUuNDYgMTcuMzdMMTUuNDYgMTcuMzdMMTUuNDYgMTguMDJRMTUuNDYgMTkuNDAgMTYuMDQgMjAuMTdRMTYuNjMgMjAuOTMgMTcuNjYgMjAuOTNMMTcuNjYgMjAuOTNRMTguODAgMjAuOTMgMTkuMjggMjAuNDJMMTkuMjggMjAuNDJMMTkuMjggMTguNzVMMTcuNTIgMTguNzVMMTcuNTIgMTcuNjJMMjAuNzYgMTcuNjJMMjAuNzYgMjAuODlRMjAuMjkgMjEuNTAgMTkuNDcgMjEuODFRMTguNjUgMjIuMTIgMTcuNjEgMjIuMTJMMTcuNjEgMjIuMTJRMTYuNTQgMjIuMTIgMTUuNzEgMjEuNjNRMTQuODkgMjEuMTQgMTQuNDQgMjAuMjRRMTMuOTkgMTkuMzMgMTMuOTcgMTguMTNaTTI2Ljk0IDIyTDI1LjQ2IDIyTDI1LjQ2IDEzLjQ3TDI2Ljk0IDEzLjQ3TDI2Ljk0IDIyWk0zMy40MyAxNC42NkwzMC43OSAxNC42NkwzMC43OSAxMy40N0wzNy41NiAxMy40N0wzNy41NiAxNC42NkwzNC45MCAxNC42NkwzNC45MCAyMkwzMy40MyAyMkwzMy40MyAxNC42NloiIGZpbGw9IiNGRkZGRkYiLz48cGF0aCBjbGFzcz0ic3ZnX190ZXh0IiBkPSJNNjYuMTYgMjJMNjMuNzggMjJMNjMuNzggMTMuNjBMNjYuMTYgMTMuNjBMNjYuMTYgMTYuNzZMNjkuNDAgMTYuNzZMNjkuNDAgMTMuNjBMNzEuNzcgMTMuNjBMNzEuNzcgMjJMNjkuNDAgMjJMNjkuNDAgMTguNzJMNjYuMTYgMTguNzJMNjYuMTYgMjJaTTc2Ljg2IDE4LjI2TDc2Ljg2IDE4LjI2TDc2Ljg2IDEzLjYwTDc5LjI0IDEzLjYwTDc5LjI0IDE4LjE5UTc5LjI0IDIwLjIwIDgwLjgzIDIwLjIwTDgwLjgzIDIwLjIwUTgyLjQyIDIwLjIwIDgyLjQyIDE4LjE5TDgyLjQyIDE4LjE5TDgyLjQyIDEzLjYwTDg0Ljc2IDEzLjYwTDg0Ljc2IDE4LjI2UTg0Ljc2IDIwLjEzIDgzLjcyIDIxLjE1UTgyLjY4IDIyLjE3IDgwLjgxIDIyLjE3TDgwLjgxIDIyLjE3UTc4Ljk0IDIyLjE3IDc3LjkwIDIxLjE1UTc2Ljg2IDIwLjEzIDc2Ljg2IDE4LjI2Wk05NC4zOSAyMkw4OS44NSAyMkw4OS44NSAxMy42MEw5NC4xNSAxMy42MFE5NS43NSAxMy42MCA5Ni41OSAxNC4xOVE5Ny40MyAxNC43OSA5Ny40MyAxNS43OUw5Ny40MyAxNS43OVE5Ny40MyAxNi4zOSA5Ny4xNCAxNi44N1E5Ni44NCAxNy4zNCA5Ni4zMCAxNy42Mkw5Ni4zMCAxNy42MlE5Ny4wMiAxNy44NyA5Ny40MyAxOC40MVE5Ny44NCAxOC45NCA5Ny44NCAxOS43MEw5Ny44NCAxOS43MFE5Ny44NCAyMC44MCA5Ni45NSAyMS40MFE5Ni4wNiAyMiA5NC4zOSAyMkw5NC4zOSAyMlpNOTIuMjAgMTguNThMOTIuMjAgMjAuMjhMOTQuMTkgMjAuMjhROTUuNDQgMjAuMjggOTUuNDQgMTkuNDNMOTUuNDQgMTkuNDNROTUuNDQgMTguNTggOTQuMTkgMTguNThMOTQuMTkgMTguNThMOTIuMjAgMTguNThaTTkyLjIwIDE1LjMxTDkyLjIwIDE2Ljk0TDkzLjgzIDE2Ljk0UTk1LjAzIDE2Ljk0IDk1LjAzIDE2LjEyTDk1LjAzIDE2LjEyUTk1LjAzIDE1LjMxIDkzLjgzIDE1LjMxTDkzLjgzIDE1LjMxTDkyLjIwIDE1LjMxWiIgZmlsbD0iI0ZGRkZGRiIgeD0iNjIuNTkiLz48L3N2Zz4=)](https://forthebadge.com)

**Comment by ekfuhrmann** [comment]
[Check out the **Important** section in the README.](https://github.com/BraveUX/for-the-badge#important)

> ## Important
> The **Copy Markdown** output is in Base64 so as to not need the badge to be hosted anywhere. This unfortunately means that it will not render in many markdown programs due to security issues, [though there have been numerous](https://github.com/github/markup/issues/270) [submissions to account for this](https://github.com/gjtorikian/html-pipeline/pull/227). Nonetheless, should you wish to include one of these badges in your own markdown where it fails to support Base64, I suggest you download the badge, and then upload it to the project you wish for it to render in. It's a minor inconvenience, but it sure is better than nothing.
> 
> Not good enough? Well you could also [submit a pull request](#contributing) for the badge to be hosted on our [For The Badge](https://forthebadge.com/) site.

**Comment by CodingSpecies** [comment]
@ekfuhrmann , thank you.
