### ISSUE TITLE
Using custom icons in the badge

### ISSUE THREAD

**Issue by lnxpy** [BraveUX/for-the-badge#182]
That would be super cool if users be able to use custom icons in their badges like using [Simple Icons](https://simpleicons.org/) for example.

**Comment by ekfuhrmann** [comment]
That might be a good solution to be honest. I've started working on including icons, but the process of having users upload an icon, then clean it using something like SVGO, and then making sure it works with all of the custom spacing was a real headache. Using a library such as this alleviates some of those pain points as I can have some control over the format. Next time I have time to work on this I'll probably go this route.

Thanks for the suggestion.
