### ISSUE TITLE
Web Share API Share button is defaulting on some browsers and removing default shareable actions

### ISSUE THREAD

**Issue by andrewsbarbaro** [BraveUX/for-the-badge#264]
In some browsers, the web share API is available causing the 3 shareable actions buttons (copy PNG, copy SVG and copy Markdown) to be hidden in place of the share button. 

The intention was to only active the web share API if the user is on a mobile device.

Reported by @tahayparker

**Comment by andrewsbarbaro** [comment]
@tahayparker Resolved! Added additional checks to ensure web share is only activated when viewing on a mobile device.

**Comment by tahayparker** [comment]
ooooo this was quickk thankss🙏🖤

**Comment by tahayparker** [comment]
[![forthebadge](https://forthebadge.com/images/badges/makes-people-smile.svg)](https://forthebadge.com)

**Comment by tahayparker** [comment]
couple more nitpicks if i may:

- the website signs you off pretty quick, any way to disable that?
- there's no copy button for "my generated badges". if i lose the code, that color combination may never be remade :(
- for some weird reason changelogs has a permanent red dot on it, even after ive seen the changelog

**Comment by andrewsbarbaro** [comment]
Thank you for this feedback! @tahayparker 

> * the website signs you off pretty quick, any way to disable that?

We will investigate this and increase session length, thank you for this feedback.

> * there's no copy button for "my generated badges". if i lose the code, that color combination may never be remade :(

This is super important and we totally agree. We will include this in our next release.

 > * for some weird reason changelogs has a permanent red dot on it, even after ive seen the changelog

This has been resolved in tonights release, another 🐞 squashed.

**Comment by tahayparker** [comment]
> We will investigate this and increase session length, thank you for this feedback.

i think i fixed this, had to enable third party cookies because auth0 has the logins

feature request: let us add profile pics, since they're coming from gravatar anyways

**Comment by tahayparker** [comment]
> We will investigate this and increase session length, thank you for this feedback.


i think i fixed this, had to enable third party cookies because auth0 has the logins

feature request: let us add profile pics please (i like seeing the garfield pic everywhere)

**Comment by andrewsbarbaro** [comment]
Hey @tahayparker, Thanks so much for the feedback. We have added Profile Pics to our feature requests.

In the meantime, we just released some massive improvements to the "My Badges" page which include a few features that highlight some of your previous feedback!  You are now able to view and copy each property of a previously generated badge. You can now also click the 'Edit with generator' button and you will be taken to the generator preloaded with the specific badge's properties.

Check it out and let us know what you think! Cheers 👏

<img width="1694" alt="Screenshot 2024-02-24 at 1 00 34 AM" src="https://github.com/forthebadge/for-the-badge/assets/106615757/00c052a8-86e0-45d7-88ac-b203a789f920">

**Comment by tahayparker** [comment]
this is soo coool mann i didnt expect this much tbh
omw to make some badges now :)
and thanks for considering profile pics!

**Comment by tahayparker** [comment]
small issue
consider implementing a function that changes the color of the copy buttons when contrast isn't good enough for the buttons to be seen

![image](https://github.com/forthebadge/for-the-badge/assets/98612931/1b875cd7-a84b-4688-a0a5-854c41364a53)

**Comment by tahayparker** [comment]
please fix bottom whitespace here when there page is too short
![image](https://github.com/forthebadge/for-the-badge/assets/98612931/e8285467-517c-4305-9fdd-4a1e96f580a1)

**Comment by tahayparker** [comment]
feature requests for "my badges":
- add list view
- add copy as png svg md
- allow deleting badges
- add button in generator to add to "my badges" instead of auto-adding (either this or the one above, but both would be super!)

**Comment by andrewsbarbaro** [comment]
> please fix bottom whitespace here when there page is too short ![image](https://private-user-images.githubusercontent.com/98612931/307581936-e8285467-517c-4305-9fdd-4a1e96f580a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4OTg3MzEsIm5iZiI6MTcwODg5ODQzMSwicGF0aCI6Ii85ODYxMjkzMS8zMDc1ODE5MzYtZTgyODU0NjctNTE3Yy00MzA1LTlmZGQtNGExZTk2ZjU4MGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDIyMDAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMzE0NWM4N2I4NWIxYWMxNDdkY2E4YjA0NTU4NWU4ZTE5MmVjZmM1YzNhMGZiOWMxMzFiMWJjMDg0ZmExODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oG3SHtUvRAyzjWl7G368AsZvIXsP-lEoWRKnpXCZDI0)

Fixed!

> small issue consider implementing a function that changes the color of the copy buttons when contrast isn't good enough for the buttons to be seen
> 
> ![image](https://private-user-images.githubusercontent.com/98612931/307575067-1b875cd7-a84b-4688-a0a5-854c41364a53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4OTg3MzEsIm5iZiI6MTcwODg5ODQzMSwicGF0aCI6Ii85ODYxMjkzMS8zMDc1NzUwNjctMWI4NzVjZDctYTg0Yi00Njg4LWEwYTUtODU0YzQxMzY0YTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDIyMDAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNWI5ZGRkNTdkZjRiZGI4ZmQzY2FkMDFkNjZmMGYyYWQwNDliOTJkMjMxNGU1Yzc1YjEyZDUyZTE1NjU1N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vQ7YjTX4VFjpfa0d0iaVvP3F_F3x7ozv_l9uSv44RhY)

and Fixed!

**Comment by tahayparker** [comment]
https://forthebadge.com/images/badges/works-on-my-machine.png

This image is smaller than the rest
I think it's been the same, before you took over, but it'd be great if it's fixed

The opposite is true for some other badges like this https://forthebadge.com/images/badges/powered-by-coders-sweat.svg

it's bigger than the rest
is this a bug or a feature :)

**Comment by andrewsbarbaro** [comment]
> https://forthebadge.com/images/badges/works-on-my-machine.png
> 
> This image is smaller than the rest I think it's been the same, before you took over, but it'd be great if it's fixed
> 
> The opposite is true for some other badges like this https://forthebadge.com/images/badges/powered-by-coders-sweat.svg
> 
> it's bigger than the rest is this a bug or a feature :)

We have been meaning to fix this for a while now but have just been focused on other features. I just fixed the sizing on both of these badges 😄 I invalidated our CDN so changes should take affect within 12 hours or on a cache clear!

**Comment by tahayparker** [comment]
it's working! 🥳🥳

**Comment by tahayparker** [comment]
found three more svgs with the same issue
https://forthebadge.com/images/badges/contains-17-coffee-cups.svg
https://forthebadge.com/images/badges/contains-breadcrumbs.svg
https://forthebadge.com/images/badges/powered-by-pull-requests.svg

fix them whenever, im sure you have more important stuff going on (like that app coming out this spring, glad i checked linkedin)

**Comment by andrewsbarbaro** [comment]
> found three more svgs with the same issue https://forthebadge.com/images/badges/contains-17-coffee-cups.svg https://forthebadge.com/images/badges/contains-breadcrumbs.svg https://forthebadge.com/images/badges/powered-by-pull-requests.svg
> 
> fix them whenever, im sure you have more important stuff going on (like that app coming out this spring, glad i checked linkedin)

Fixed!
