### ISSUE TITLE
Updates on the project

### ISSUE THREAD

**Issue by loorlab** [BraveUX/for-the-badge#29]
Greetings friends, the project is abandoned?

Thanks !

**Comment by christoga** [comment]
I think so, even though I really like this project, There hasn't been any commits since last month.

**Comment by Viltaria** [comment]
I might make a few If someone would tell me where to start, could anyone?

**Comment by loorlab** [comment]
Hi Viltaria : https://github.com/BraveUX/for-the-badge/pull/18 Thanks !

**Comment by ekfuhrmann** [comment]
Hi All,

I will be taking over this project and taking care of any requests that have been and may be made in the future.  Apologies for the lapse in activity here, but better late than never!
