### ISSUE TITLE
HTTPS the site

### ISSUE THREAD

**Issue by TheDeadCode** [BraveUX/for-the-badge#31]
So it stops killing the SSL certificates in the page it's embedded in.

**Comment by christoga** [comment]
I'm sorry, what are you asking about?

**Comment by TheDeadCode** [comment]
Add an SSL certificate on http://forthebadge.com.
You can use LetsEncrypt.

**Comment by TheDeadCode** [comment]
The reason why I ask to make it SSL is because I run gitlab and it breaks the SSL to have a non-ssl resource in the readme.

I had to make a SSL version [here](https://badges.vynatu.io/) (On a CDN for people who like speed) to make it work properly.

**Comment by ekfuhrmann** [comment]
Way overdue.  Site now redirects to HTTPS.
