### ISSUE TITLE
copy dosnt work for me

### ISSUE THREAD

**Issue by treaki** [BraveUX/for-the-badge#33]
neither on firefox nor on opera i am able to get anything to the clipboard. for me it just lukes like theese buttons dont produce a reaction on click at all

please fix that

thanks

**Comment by treaki** [comment]
i am not very in to these js thingies, but first of all i guess it wouldnt be bad to write something to the debug console if the function who is in charge to copy something to clipboard is called... i also tryed the debug button but there is just one line of code where should be at least hundred (rough guess considering the lengh of the line) i dont want to go this through with non exisiting knowledge of javascript

**Comment by notnsane** [comment]
I can confirm that it doesn't work for me either. Tried with Edge, Vivaldi and Firefox on Windows x64. JS is enabled and works everywhere including clipboardjs.com

**Comment by christoga** [comment]
It works for me tho.

**Comment by treaki** [comment]
@ekfuhrmann what information do you need and how can i gather them?

**Comment by ekfuhrmann** [comment]
What OS/Browser (with version) are you running.  With that info I should be able to recreate with Browserstack and figure out what's going on for you.

**Comment by OmgImAlexis** [comment]
The copy part needs to be replace with a non-flash version. I'm guessing that's the reason it's not working. https://clipboardjs.com/ is what a lot of projects are now using instead of whatever you're using right now.

**Comment by nicholasshirley** [comment]
Copy also doesn't work for me
Mac OS 10.12.3
Chrome 56.0.2924.87 (64-bit)

**Comment by OmgImAlexis** [comment]
@ekfuhrmann can you please replace it with the clipboardjs library I suggested.

**Comment by ekfuhrmann** [comment]
@OmgImAlexis Thanks for the library. I've got this running locally and will be rolling it out in an upcoming build shortly!

**Comment by ekfuhrmann** [comment]
[Fix Can Be Found Here](4c15cf893bc6245e243095923c21501c8765a4a8)
