### ISSUE TITLE
add favicon

### ISSUE THREAD

**Issue by treaki** [BraveUX/for-the-badge#34]
lokes like you have got a nice logo which meats the requirements (square) for a favicon. Why not add that to make the tab in the browser a bit more then justtext. To copy the attached file to the root folder of the site (as http://forthebadge.com/favicon.ico ) would be enough to accomplice this.

regards

[ftb-favicon.zip](https://github.com/BraveUX/for-the-badge/files/482191/ftb-favicon.zip)
(i ziped it because github forced me to do...)

**Comment by christoga** [comment]
Why didnt yoi just send a PR bro😂

**Comment by ekfuhrmann** [comment]
Added in an upcoming build.
