### ISSUE TITLE
Any chance we could get versions that match the sizing of TravisCI?

### ISSUE THREAD

**Issue by gileswells** [BraveUX/for-the-badge#38]
Right now the badges are huge in comparison so it stands out. I think it would be great to be able to sneak one in there and not have people notice but to do that it would have to be the same sizing.

**Comment by Ionaru** [comment]
You can generate any TravisCI-like badge on https://shields.io at 'your badge' near the bottom

https://img.shields.io/badge/hello-gileswells-E962A5.svg
![](https://img.shields.io/badge/hello-gileswells-E962A5.svg)

https://img.shields.io/badge/spam-sausage-red.svg
![](https://img.shields.io/badge/spam-sausage-red.svg)

https://img.shields.io/badge/build-banana-yellow.svg
![](https://img.shields.io/badge/build-banana-yellow.svg)

**Comment by ekfuhrmann** [comment]
Like @Ionaru said, you can generate any TravisCI-like badge at the URL he provided. If you want to keep consistency with TravisCI badges, I suggest you do that.
