### ISSUE TITLE
Update site to include newest commits for size

### ISSUE THREAD

**Issue by timfallmk** [BraveUX/for-the-badge#39]
Looks like the site needs a rebuild to include 6c746915911ce3fa06f940f3675a13bfeb78ab70 (and maybe others).

Currently the svgs are still being rendered at full size.

**Comment by timfallmk** [comment]
Oh, and great job! :neckbeard:

**Comment by ekfuhrmann** [comment]
I have an update coming soon which will update all of the badges and include the fixed badge size commit for every badge.

I wanted to shift over from the paid fonts we were using to free ones, so this seemed like as good a time as any to just knock out two birds with one stone. Thanks for the heads up!
