### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by SimulatedGREG** [BraveUX/for-the-badge#41]
@BraveUX

Not sure if this is maintenance, but my badges are failing to load now. Trying to the visit the site yields 
![image](https://cloud.githubusercontent.com/assets/8327811/21916756/3c9e315c-d908-11e6-9dd7-07e4a7152596.png)

**Comment by jsbUSMC** [comment]
It has been down for the past few days

**Comment by gabrielstuff** [comment]
Will it come back ?

**Comment by Efreak** [comment]
http://forthebadge.com/ working fine for me...

**Comment by SimulatedGREG** [comment]
Oh hey, it is back up! Thanks to whoever fixed it. My README looks a lot better now, haha. Thanks for such awesome badges @BraveUX.
