### ISSUE TITLE
Built for Android Badge is too large in Read Me files

### ISSUE THREAD

**Issue by TheRealGitCub** [BraveUX/for-the-badge#55]
Example: https://github.com/TheRealGitCub/GSCampusMap/blob/a80c197b16d780d61cabcaa7cad1d8973faac1d8/README.md

**Comment by ekfuhrmann** [comment]
[![forthebadge](http://forthebadge.com/images/badges/built-for-android.svg)](http://forthebadge.com)

Lost relative sizing on this badge. Should be resolved now!
