### ISSUE TITLE
other languages "Made with" badge request

### ISSUE THREAD

**Issue by mortza** [BraveUX/for-the-badge#56]
it would be nice if you create "made with" badge for other languages like C++,C ,....

**Comment by symoN5** [comment]
yeah, would be cool to see

**Comment by klud1** [comment]
+1 to this, would love to see one with Go though <3

**Comment by shevegen** [comment]
I assume that Eric and others may perhaps add more badges. Let's try to come up with a list of which languages would be most wanted on top of the ones already available?

So far we have mentions of:

- C++
- C
- Go

**Comment by Sayan98** [comment]
How about Haskell / Scala ?

**Comment by agarcialeon** [comment]
How about selecting top languages used in Github repositories? See this [Github Topics](https://github.com/topics)

**Comment by binakot** [comment]
Java!

**Comment by ekfuhrmann** [comment]
I added C++, C, Go, Java, and Javascript.

If you guys want any others added, it helps a bunch to make a PR with the badge you want because there is no way I'm making a badge for every language in [Github Topics](https://github.com/topics).
