### ISSUE TITLE
add repository:deprecated or something similar

### ISSUE THREAD

**Issue by stendarr** [BraveUX/for-the-badge#59]
It would be nice to have a possibility to show that a repository is deprecated/discontinued/unmaintained or whatever you want to call it.

**Comment by ekfuhrmann** [comment]
Sure, but this repo is still active, albeit updates aren't done incredibly frequently.

That said, I plan to knock out some of the PRs relatively soon.

**Comment by stendarr** [comment]
I didn't mean for this repo, but a general button to use for showing the deprecation of a repository.

**Comment by stendarr** [comment]
@ekfuhrmann Let me get this straight so you understand it. I want a badge that says deprecated so I can use it on MY repo. I don't want this repo to be labelled as deprecated.

**Comment by ekfuhrmann** [comment]
Got it, thanks for clearing that up!

I don't think it works in the context of our site. While we do have some functional badges, for all intents and purposes this project is a parody of repo badges and supposed to be humorous in context.

[Repo Badges should cover more of what you're looking for in regards to actual functional badges.](https://github.com/dwyl/repo-badges)
