### ISSUE TITLE
Badge design tutorial

### ISSUE THREAD

**Issue by scout119** [BraveUX/for-the-badge#69]
I think it would help a to engage contributions of new badges if there is a tutorial on how to make one. A simple, visual step by step instructions using a free application like InkScape.

Something similar to the tutorials here http://www.2dgameartguru.com/

Thank you.

**Comment by ekfuhrmann** [comment]
This is a great suggestion. As evidence by the lack of updates to this repo over the past few ~~months~~ years, I just don't have the bandwidth to put towards this ask. Should anyone be interested in putting together a more fleshed out step-by-step for such a process, I'd be happy to work with that individual and we could perhaps add a guide to the Wiki that we reference.

Nonetheless thanks for the suggestion and support!
