### ISSUE TITLE
Website SSL Certificate is EXPIRED

### ISSUE THREAD

**Issue by eai04191** [BraveUX/for-the-badge#74]
Please Renew Certificate as soon as possible.

https://www.ssllabs.com/ssltest/analyze.html?d=forthebadge.com&latest

**Comment by davidgoate** [comment]
This is slightly annoying, in IDE's like IntelliJ it attempts to render markdown when the plugin is installed which means every time I open the readme or I perform an SCN update which modifies the Readme I get this lovely blocking modal:
<img width="562" alt="screen shot 2018-06-25 at 17 12 42" src="https://user-images.githubusercontent.com/8789912/41862247-3d0b76a2-789b-11e8-9c93-6623b6d8cc2a.png">

**Comment by ekfuhrmann** [comment]
We've gone ahead and renewed the certificate. Sorry for the drop in service and any inconvenience.

**Comment by davidgoate** [comment]
@ekfuhrmann thanks!
