### ISSUE TITLE
made with/wordpad badge request

### ISSUE THREAD

**Issue by kiedtl** [BraveUX/for-the-badge#87]
I really liked the "designed in/ms paint" badge. Try making a "made in/wordpad" badge.

**Comment by ArelySkywalker** [comment]
@kiedtl I loved your idea! I made a pull request for that badge
#90

**Comment by ekfuhrmann** [comment]
Thanks @ArelySkywalker for picking this up. I added some comments to your PR in order to get that badge created.

Apologies for the long delay in triaging this repo!
