### ISSUE TITLE
add .jshintrc

### ISSUE THREAD

**Issue by callmecavs** [BraveUX/for-the-badge#9]

**Comment by stevelacy** [comment]
The `.jshintrc` we use:
Resource for options: http://jshint.com/docs/options/
```json
{
  "camelcase": true,
  "curly": true,
  "eqeqeq": true,
  "freeze": true,
  "indent": 2,
  "newcap": false,
  "quotmark": "single",
  "maxdepth": 5,
  "maxstatements": 50,
  "maxlen": 100,
  "eqnull": true,
  "funcscope": true,
  "strict": true,
  "undef": true,
  "unused": true,
  "node": true,
  "mocha": true
}
```
It is quite strict, but does produce very clean code. If you need any explanations, just ask :)

We also have a `.editorconfig` which sublime, atom, etc support.
```coffee
# editorconfig.org
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

When the user saves the file the editor will parse it with the `.editorconfig` options, such as auto-removing trailing whitespace.
